"""empty message

Revision ID: f0d2188e0b43
Revises: 906bcfa54a55
Create Date: 2020-02-17 12:41:51.967034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d2188e0b43'
down_revision = '906bcfa54a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('upvotes_upvote_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_upvote_fkey', 'upvotes', 'pitches', ['upvote'], ['id'])
    op.drop_column('upvotes', 'pitch_id')
    # ### end Alembic commands ###
